name: Nightly Pipeline

on:
  workflow_dispatch:
    inputs:
      dryrun:
        type: boolean
        default: false
  schedule:
    - cron: '0 0 * * *'

jobs:
  PackageUpdate:
    name: Nightly Package Update
    uses: 51Degrees/common-ci/.github/workflows/nightly-package-update.yml@nightly-pipeline
    with:
      common-ci-ref: nightly-pipeline
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}

  SubmoduleUpdate:
    name: Nightly Submodule Update
    uses: 51Degrees/common-ci/.github/workflows/nightly-submodule-update.yml@nightly-pipeline
    with:
      common-ci-ref: nightly-pipeline
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}

  PullRequests:
    if: ${{ !cancelled() }}
    needs: [PackageUpdate, SubmoduleUpdate]
    name: Nightly Pull Requests
    uses: 51Degrees/common-ci/.github/workflows/nightly-pull-requests.yml@nightly-pipeline
    with:
      common-ci-ref: nightly-pipeline
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
      cache-assets: true
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
      DeviceDetection: ${{ secrets.DEVICE_DETECTION_KEY }}
      DeviceDetectionUrl: ${{ secrets.DEVICE_DETECTION_URL }}
      TestResourceKey: ${{ secrets.SUPER_RESOURCE_KEY}}
      AcceptCHBrowserKey: ${{ secrets.ACCEPTCH_BROWSER_KEY}}
      AcceptCHHardwareKey: ${{ secrets.ACCEPTCH_HARDWARE_KEY}}
      AcceptCHPlatformKey: ${{ secrets.ACCEPTCH_PLATFORM_KEY}}
      AcceptCHNoneKey: ${{ secrets.ACCEPTCH_NONE_KEY}}
